name: Build Custom AMI  # ✅ Change this to your preferred workflow name

on:
  release:
    types: [published]  # ✅ Trigger this workflow when a new GitHub release is published

env:
  AWS_REGION: "eu-west-1"       # ✅ Update if your AWS region is different
  PACKER_VERSION: "1.11.2"      # ✅ You can upgrade if a newer version is available

jobs:
  build_image:
    name: packer build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1 - Checkout Repository
      - name: Repository Checkout
        uses: actions/checkout@v4

      # Step 2 - Install packer
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PACKER_VERSION }}

      # Step 3 - Packer init
      - name: Run `packer init`
        id: init
        run: packer init ./image.pkr.hcl  # ✅ Update path if your file is elsewhere

      # Step 4 - Setup AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}  # ✅ Make sure this secret is defined
          aws-region: ${{ env.AWS_REGION }}

      # Step 5 - Save secrets to secrets.sh (so they're baked into the AMI)
      - name: Save secrets to secrets.sh
        run: |
          echo "#!/bin/bash" > $GITHUB_WORKSPACE/secrets.sh
          echo "export SECRET_KEY='${{ secrets.SECRET_KEY }}'" >> $GITHUB_WORKSPACE/secrets.sh
          echo "export DB_USER='${{ secrets.DB_USER }}'" >> $GITHUB_WORKSPACE/secrets.sh
          echo "export DB_PASSWORD='${{ secrets.DB_PASSWORD }}'" >> $GITHUB_WORKSPACE/secrets.sh

      # Step 6 - Build the custom AMI with Packer
      - name: Run `packer build`
        run: |
          packer build -color=false
